spring:
  profiles:
    active:
      dev

application:
  security:
    jwt:
      secret-key:
        404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration:
        315576000000 # 10 years
      refresh-token:
        expiration:
          315576000000 # 10 years



attach:
  upload:
    folder:
      attaches/

  download:
    url:
      ${app.url}/attach/public/open/